services:
  - type: web
    name: pans-unizik-election-api
    runtime: node
    plan: free
    rootDir: election-site
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: COOKIE_SAMESITE
        value: None
      - key: CORS_ORIGIN
        value: https://election-site-zeta.vercel.app,http://localhost:3000
